services:
  db:
    image: postgres:18-alpine
    container_name: aspnet_users_products_db
    environment:
      POSTGRES_DB: users_products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users_products_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet_users_products_api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=users_products_db;Username=postgres;Password=postgres
      Jwt__Issuer: UsersProducts.Api
      Jwt__Audience: UsersProducts.Client
      Jwt__SecretKey: clave-super-secreta-de-desarrollo-con-mas-de-32-caracteres
      Jwt__ExpirationMinutes: 60
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge